export const EventTypes = {
  BUDGET_CREATED: 'BUDGET_CREATED',
  BUDGET_APPROVED: 'BUDGET_APPROVED',
  BUDGET_REJECTED: 'BUDGET_REJECTED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  OS_CREATED: 'OS_CREATED',
  OS_ACCEPTED: 'OS_ACCEPTED',
  OS_BUDGET_APPROVED: 'OS_BUDGET_APPROVED',
  OS_BUDGET_REJECTED: 'OS_BUDGET_REJECTED',
} as const;
